[package]
name = "easyfix-dictionary"
version = "0.20.0"
authors = ["Łukasz Dańko <lukasz.danko@gmail.com>"]
license = "MIT"
description = "Easy FIX (Financial Information Exchange) toolset - messages dictionary."
repository = "https://github.com/ldanko/easyfix"
readme = "README.md"
edition = "2024"
rust-version = "1.96.0"

[lints]
workspace = true

[dependencies]
easyfix-core = { workspace = true, features = ["serde-serialize", "serde-deserialize"] }
quick-xml = { version = "0.37.2", features = ["serialize"] }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
xmltree = "0.10"

[dev-dependencies]
uuid = { version = "1.8.0", features = ["v4"] }
