name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy
    - name: Build
      run: cargo build --verbose
    - name: Fmt
      run: |
        cargo fmt --check --verbose
        cargo clippy -- -D warnings

    # Skip for now, because tests are always failing
    # - name: Run tests
    #   run: cargo test --verbose
